<html>

<?php include("menu.php"); ?>

<head>
<title>Grade 1</title>
</head>

<body>
<p><h3><a href="http://www.westonschools.org/" target=_new>Country School</a>: Grade 1<br>
C. Dailey</h3>

<p><TABLE CELLSPACING = 1 CELLPADDING = 0 BORDER = 1 BORDERCOLOR = #000000 WIDTH = 600>

<TR>
<TD><CENTER>Subject</CENTER></TD>
<TD><CENTER>FEB Excellent</CENTER></TD>
<TD><CENTER>FEB Very Good</CENTER></TD>
<TD><CENTER>FEB Satisfactory</CENTER></TD>
<TD><CENTER>FEB Needs Improve</CENTER></TD>
<TD><CENTER>JUN Excellent</CENTER></TD>
<TD><CENTER>JUN Very Good</CENTER></TD>
<TD><CENTER>JUN Satisfactory</CENTER></TD>
<TD><CENTER>JUN Needs Improve</CENTER></TD>

<TR>
<TD><CENTER>Math: Application of concepts</CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Math: Computational Skills</CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Math: Problem solving Skills</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Math: Effort</CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Reading: Phonics and Other Word Attack skills</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Reading: Comprehension skills</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Reading: Oral Reading</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Reading: Recreational Reading</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Reading: Effort</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Language Arts: Oral Expression</CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Language Arts: Written Expression</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Language Arts: Handwriting</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Language Arts: Spelling</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Language Arts: Listening Skills</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Language Arts: Effort</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Social Studies: Participation</CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Science: Participation</CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Art: Participation</CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Music: Participation</CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Work Habits: Following Directions</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Work Habits: Completing Assignments on Time</CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Work Habits: Using Time Effectively</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>Work Habits: Listening</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>X</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

</TABLE>

</body>

</html>

