<html>

<?php include("menu.php"); ?>

<head>
<title>Freshman Year</title>
</head>

<body>
<p><h3><a href="http://www.wheaton.edu/" target=_new>Wheaton College</a>: Freshman</h3>

<p><TABLE CELLSPACING = 1 CELLPADDING = 0 BORDER = 1 BORDERCOLOR = #000000 WIDTH = 600>

<TR>
<TD><CENTER>Department</CENTER></TD>
<TD><CENTER>Title</CENTER></TD>
<TD><CENTER>Hours</CENTER></TD>
<TD><CENTER>Grade</CENTER></TD>
<TD><CENTER>Points</CENTER></TD>
<TD><CENTER>Sem GPA</CENTER></TD>
<TD><CENTER>Cum GPA</CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>Credit by AP Exam</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>Biology (4)</CENTER></TD>
<TD><CENTER>4</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>Computer Science (5)</CENTER></TD>
<TD><CENTER>4</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>Calculus BC (5)</CENTER></TD>
<TD><CENTER>6</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>European History (3)</CENTER></TD>
<TD><CENTER>2</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>=16</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>FALL 1994</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>BITH 111</CENTER></TD>
<TD><CENTER>Theology of Culture</CENTER></TD>
<TD><CENTER>2</CENTER></TD>
<TD><CENTER>A-</CENTER></TD>
<TD><CENTER>7.4</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>CHEM 231</CENTER></TD>
<TD><CENTER>General Chemistry I</CENTER></TD>
<TD><CENTER>4</CENTER></TD>
<TD><CENTER>B+</CENTER></TD>
<TD><CENTER>13.2</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>ENGL 101</CENTER></TD>
<TD><CENTER>Lit of Western World</CENTER></TD>
<TD><CENTER>4</CENTER></TD>
<TD><CENTER>A-</CENTER></TD>
<TD><CENTER>14.8</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>G ST 131</CENTER></TD>
<TD><CENTER>Small Group Practm</CENTER></TD>
<TD><CENTER>2</CENTER></TD>
<TD><CENTER>A-</CENTER></TD>
<TD><CENTER>7.4</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>HNGR 112</CENTER></TD>
<TD><CENTER>Third World Issues</CENTER></TD>
<TD><CENTER>2</CENTER></TD>
<TD><CENTER>B</CENTER></TD>
<TD><CENTER>6.0</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>IDS 110</CENTER></TD>
<TD><CENTER>Freshman Experience</CENTER></TD>
<TD><CENTER>1</CENTER></TD>
<TD><CENTER>A</CENTER></TD>
<TD><CENTER>4.0</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>P E 000</CENTER></TD>
<TD><CENTER>Swim Test</CENTER></TD>
<TD><CENTER>0</CENTER></TD>
<TD><CENTER>P</CENTER></TD>
<TD><CENTER>0.0</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>P E 101</CENTER></TD>
<TD><CENTER>Foundations</CENTER></TD>
<TD><CENTER>1</CENTER></TD>
<TD><CENTER>A</CENTER></TD>
<TD><CENTER>4.0</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>3.55</CENTER></TD>
<TD><CENTER>3.55</CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>SPRING 1995</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>ART 101</CENTER></TD>
<TD><CENTER>Art Survey</CENTER></TD>
<TD><CENTER>2</CENTER></TD>
<TD><CENTER>C+</CENTER></TD>
<TD><CENTER>4.6</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>CHEM 233</CENTER></TD>
<TD><CENTER>Inorg/Analytcl Chem</CENTER></TD>
<TD><CENTER>4</CENTER></TD>
<TD><CENTER>B</CENTER></TD>
<TD><CENTER>12.0</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>ENGW 103</CENTER></TD>
<TD><CENTER>Writing Effect Prose</CENTER></TD>
<TD><CENTER>4</CENTER></TD>
<TD><CENTER>B</CENTER></TD>
<TD><CENTER>12.0</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>P E 139</CENTER></TD>
<TD><CENTER>Tennis</CENTER></TD>
<TD><CENTER>1</CENTER></TD>
<TD><CENTER>B</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>PHIL 101</CENTER></TD>
<TD><CENTER>Issues/World Views</CENTER></TD>
<TD><CENTER>4</CENTER></TD>
<TD><CENTER>B</CENTER></TD>
<TD><CENTER>12.0</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>2.91</CENTER></TD>
<TD><CENTER>3.24</CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>SUMMER 1995</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>GREK 101</CENTER></TD>
<TD><CENTER>Elementary Greek I</CENTER></TD>
<TD><CENTER>4</CENTER></TD>
<TD><CENTER>A</CENTER></TD>
<TD><CENTER>16.0</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>GREK 102</CENTER></TD>
<TD><CENTER>Elementary Greek II</CENTER></TD>
<TD><CENTER>4</CENTER></TD>
<TD><CENTER>B+</CENTER></TD>
<TD><CENTER>13.2</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>3.65</CENTER></TD>
<TD><CENTER>3.32</CENTER></TD>

</TABLE>

</body>

</html>

