<html>

<?php include("menu.php"); ?>

<head>
<title>Junior Year</title>
</head>

<body>
<p><h3><a href="http://www.wheaton.edu/" target=_new>Wheaton College</a>: Junior</h3>

<p><TABLE CELLSPACING = 1 CELLPADDING = 0 BORDER = 1 BORDERCOLOR = #000000 WIDTH = 600>

<TR>
<TD><CENTER>Department</CENTER></TD>
<TD><CENTER>Title</CENTER></TD>
<TD><CENTER>Hours</CENTER></TD>
<TD><CENTER>Grade</CENTER></TD>
<TD><CENTER>Points</CENTER></TD>
<TD><CENTER>Sem GPA</CENTER></TD>
<TD><CENTER>Cum GPA</CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>SUMMER 1996</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>Harvard Univ, Cambridge, MA</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>CHIN S-A</CENTER></TD>
<TD><CENTER>Elementary Modern Chinese I</CENTER></TD>
<TD><CENTER>4</CENTER></TD>
<TD><CENTER>A</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>CHIN S-B</CENTER></TD>
<TD><CENTER>Elementary Modern Chinese II</CENTER></TD>
<TD><CENTER>4</CENTER></TD>
<TD><CENTER>A</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>=8</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>FALL 1996</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>BITH 212</CENTER></TD>
<TD><CENTER>OT Lit & Interp</CENTER></TD>
<TD><CENTER>2</CENTER></TD>
<TD><CENTER>B</CENTER></TD>
<TD><CENTER>6.0</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>HIST 105</CENTER></TD>
<TD><CENTER>Hist of Civilization</CENTER></TD>
<TD><CENTER>4</CENTER></TD>
<TD><CENTER>B</CENTER></TD>
<TD><CENTER>12.0</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>PHIL 311</CENTER></TD>
<TD><CENTER>Hist of Philosophy</CENTER></TD>
<TD><CENTER>4</CENTER></TD>
<TD><CENTER>B</CENTER></TD>
<TD><CENTER>12.0</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>PHIL 315</CENTER></TD>
<TD><CENTER>Phil of Religion</CENTER></TD>
<TD><CENTER>4</CENTER></TD>
<TD><CENTER>B-</CENTER></TD>
<TD><CENTER>10.8</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>2.91</CENTER></TD>
<TD><CENTER>3.27</CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>SPRING 1997</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>B/EC 211</CENTER></TD>
<TD><CENTER>Microecon Principles</CENTER></TD>
<TD><CENTER>4</CENTER></TD>
<TD><CENTER>A-</CENTER></TD>
<TD><CENTER>14.8</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>BITH 374</CENTER></TD>
<TD><CENTER>Systematic Theology</CENTER></TD>
<TD><CENTER>4</CENTER></TD>
<TD><CENTER>A-</CENTER></TD>
<TD><CENTER>14.8</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>PHIL 312</CENTER></TD>
<TD><CENTER>Hist of Philosophy</CENTER></TD>
<TD><CENTER>4</CENTER></TD>
<TD><CENTER>B</CENTER></TD>
<TD><CENTER>12.0</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>3.47</CENTER></TD>
<TD><CENTER>3.29</CENTER></TD>

</TABLE>

</body>

</html>

