<html>

<?php include("menu.php"); ?>

<head>
<title>First Year</title>
</head>

<body>
<p><h3><a href="http://www.gordonconwell.edu/" target=_new>Gordon-Conwell Theological Seminary</a>: First Year</h3>

<p><TABLE CELLSPACING = 1 CELLPADDING = 0 BORDER = 1 BORDERCOLOR = #000000 WIDTH = 600>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>Class</CENTER></TD>
<TD><CENTER>Hours</CENTER></TD>
<TD><CENTER>Grade</CENTER></TD>
<TD><CENTER>GPA</CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>FALL 1998</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>CE102</CENTER></TD>
<TD><CENTER>Educational Ministry of the Church</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>A</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>GL101</CENTER></TD>
<TD><CENTER>Basic Greek I</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>A</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>MC101</CENTER></TD>
<TD><CENTER>Spiritual Formation for Ministry</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>A-</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>MM101</CENTER></TD>
<TD><CENTER>Mentored Ministry - Unit 1<br>Non-Academic Credit</CENTER></TD>
<TD><CENTER>1.5</CENTER></TD>
<TD><CENTER>A</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>OT102</CENTER></TD>
<TD><CENTER>Introduction to the Old Testament</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>D-</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>TH104</CENTER></TD>
<TD><CENTER>Systematic Theology I</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>B-</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>ses</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>15.00</CENTER></TD>
<TD><CENTER>45.30</CENTER></TD>
<TD><CENTER>3.020</CENTER></TD>

<TR>
<TD><CENTER>cum</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>15.00</CENTER></TD>
<TD><CENTER>45.30</CENTER></TD>
<TD><CENTER>3.020</CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>JANUARY 1999</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>OT105</CENTER></TD>
<TD><CENTER>Christ in the Old Testament</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>B-</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>ses</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>3.00</CENTER></TD>
<TD><CENTER>8.10</CENTER></TD>
<TD><CENTER>2.700</CENTER></TD>

<TR>
<TD><CENTER>cum</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>18.00</CENTER></TD>
<TD><CENTER>53.40</CENTER></TD>
<TD><CENTER>2.967</CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>SPRING 1999</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>GL102</CENTER></TD>
<TD><CENTER>Basic Greek II</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>B</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>MM102</CENTER></TD>
<TD><CENTER>Mentored Ministry - Unit 2<br>Non-Academic Credit</CENTER></TD>
<TD><CENTER>1.5</CENTER></TD>
<TD><CENTER>A</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>NT102</CENTER></TD>
<TD><CENTER>Interpreting the New Testament</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>C</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>TH205</CENTER></TD>
<TD><CENTER>Systematic Theology II</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>B-</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>ses</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>9.00</CENTER></TD>
<TD><CENTER>23.10</CENTER></TD>
<TD><CENTER>2.567</CENTER></TD>

<TR>
<TD><CENTER>cum</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>27.00</CENTER></TD>
<TD><CENTER>76.50</CENTER></TD>
<TD><CENTER>2.833</CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>SUMMER 1999</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>MM201</CENTER></TD>
<TD><CENTER>Mentored Ministry - Unit 3<br>Non-Academic Credit</CENTER></TD>
<TD><CENTER>1.5</CENTER></TD>
<TD><CENTER>A</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>MM202</CENTER></TD>
<TD><CENTER>Mentored Ministry - Unit 4<br>Non-Academic Credit</CENTER></TD>
<TD><CENTER>1.5</CENTER></TD>
<TD><CENTER>A</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>CE203</CENTER></TD>
<TD><CENTER>Christian Education of Adults</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>A-</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>ses</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>11.10</CENTER></TD>
<TD><CENTER>3.700</CENTER></TD>

<TR>
<TD><CENTER>cum</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>30.00</CENTER></TD>
<TD><CENTER>87.60</CENTER></TD>
<TD><CENTER>2.920</CENTER></TD>

</TABLE>

</body>

</html>

