<html>

<?php include("menu.php"); ?>

<head>
<title>Third Year</title>
</head>

<body>
<p><h3><a href="http://www.gordonconwell.edu/" target=_new>Gordon-Conwell Theological Seminary</a>: Third Year</h3>

<p><TABLE CELLSPACING = 1 CELLPADDING = 0 BORDER = 1 BORDERCOLOR = #000000 WIDTH = 600>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>Class</CENTER></TD>
<TD><CENTER>Hours</CENTER></TD>
<TD><CENTER>Grade</CENTER></TD>
<TD><CENTER>GPA</CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>FALL 2000</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>NT640</CENTER></TD>
<TD><CENTER>Exegesis of First Peter</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>B</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>OL501</CENTER></TD>
<TD><CENTER>Hebrew I</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>A</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>PC511</CENTER></TD>
<TD><CENTER>Pastoral Counseling</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>A</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>PR602</CENTER></TD>
<TD><CENTER>Preaching for Modern Listeners</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>A</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>ses</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>12.00</CENTER></TD>
<TD><CENTER>45.00</CENTER></TD>
<TD><CENTER>3.750</CENTER></TD>

<TR>
<TD><CENTER>cum</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>63.00</CENTER></TD>
<TD><CENTER>203.10</CENTER></TD>
<TD><CENTER>3.224</CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>SPRING 2001</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>EV670</CENTER></TD>
<TD><CENTER>Urban Evangelism</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>B+</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>NT617</CENTER></TD>
<TD><CENTER>Exegesis of John</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>A-</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>SE632</CENTER></TD>
<TD><CENTER>Christianity and the Problem of Racism</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>B+</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>WM601</CENTER></TD>
<TD><CENTER>World Mission of the Church</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>A</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>ses</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>12.00</CENTER></TD>
<TD><CENTER>42.90</CENTER></TD>
<TD><CENTER>3.575</CENTER></TD>

<TR>
<TD><CENTER>cum</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>75.00</CENTER></TD>
<TD><CENTER>246.00</CENTER></TD>
<TD><CENTER>3.280</CENTER></TD>

<TR>
<TD><CENTER></CENTER></TD>
<TD><CENTER>SUMMER 2001</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>OL502</CENTER></TD>
<TD><CENTER>Hebrew II</CENTER></TD>
<TD><CENTER>3.0</CENTER></TD>
<TD><CENTER>A-</CENTER></TD>
<TD><CENTER></CENTER></TD>

<TR>
<TD><CENTER>ses</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>3.00</CENTER></TD>
<TD><CENTER>11.10</CENTER></TD>
<TD><CENTER>3.700</CENTER></TD>

<TR>
<TD><CENTER>cum</CENTER></TD>
<TD><CENTER></CENTER></TD>
<TD><CENTER>78.00</CENTER></TD>
<TD><CENTER>257.10</CENTER></TD>
<TD><CENTER>3.296</CENTER></TD>

</TABLE>

</body>

</html>

